### ISSUE TITLE
Update to angularfire2 4.0.0-rc.0

### ISSUE THREAD

**Issue by sunilkconsultant** [Inoverse/aaronczichon.de#1]
Your example code is not working with below:

```
"angularfire2": "^4.0.0-rc.0",
"firebase": "^3.9.0"
```

**Comment by Inoverse** [comment]
All sample projects are updated to the latest `AngularFire2` version (which is `4.0.0-RC.1`

**Comment by ionicmanual** [comment]
@Inoverse Thank you! Appreciate
